-- =============================================================
-- Esnafta Var - QR snapshot and merchant verification migration
-- =============================================================
-- Purpose:
-- - Freeze product name, quantity, and price when a customer creates a QR.
-- - Keep at most one active QR per cart.
-- - Cancel the active QR whenever its cart contents meaningfully change.
-- - Allow only the merchant/admin owner of the matching shop to inspect and
--   confirm a QR through narrowly scoped SECURITY DEFINER RPC functions.
-- - Complete a confirmation exactly once and check out the cart atomically.
--
-- Safety:
-- - This migration adds snapshot data and hardens existing cart write rules;
--   it is safe to re-run.
-- - It does not DROP/TRUNCATE any table or delete existing rows.
-- - Existing active QR rows without a snapshot are marked cancelled because
--   their historical price and contents cannot be verified safely.
-- - Lock acquisition and individual statements have bounded wait times; any
--   timeout aborts this transaction before a partial migration can commit.
-- - Run this file only after the profiles role, shops/shop_products, carts v2,
--   and qr_sessions migrations have completed.
-- =============================================================

BEGIN;

SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '5min';

-- ====================
-- Preconditions
-- ====================
DO $preflight$
DECLARE
  v_missing_tables TEXT;
  v_missing_columns TEXT;
BEGIN
  SELECT string_agg(required_table, ', ' ORDER BY required_table)
    INTO v_missing_tables
  FROM (
    VALUES
      ('auth.users'),
      ('public.profiles'),
      ('public.products'),
      ('public.shops'),
      ('public.shop_products'),
      ('public.carts'),
      ('public.cart_items_v2'),
      ('public.qr_sessions')
  ) AS required_tables(required_table)
  WHERE to_regclass(required_table) IS NULL;

  IF v_missing_tables IS NOT NULL THEN
    RAISE EXCEPTION
      'Required tables are missing: %. Run the prerequisite migrations first.',
      v_missing_tables
      USING ERRCODE = '42P01';
  END IF;

  SELECT string_agg(
           format('%I.%I.%I', schema_name, table_name, column_name),
           ', '
           ORDER BY schema_name, table_name, column_name
         )
    INTO v_missing_columns
  FROM (
    VALUES
      ('public', 'profiles', 'id'),
      ('public', 'profiles', 'role'),
      ('public', 'products', 'id'),
      ('public', 'products', 'name'),
      ('public', 'shops', 'id'),
      ('public', 'shops', 'owner_user_id'),
      ('public', 'shops', 'name'),
      ('public', 'shops', 'is_active'),
      ('public', 'shop_products', 'id'),
      ('public', 'shop_products', 'shop_id'),
      ('public', 'shop_products', 'product_id'),
      ('public', 'shop_products', 'price'),
      ('public', 'shop_products', 'is_active'),
      ('public', 'shop_products', 'is_available'),
      ('public', 'carts', 'id'),
      ('public', 'carts', 'user_id'),
      ('public', 'carts', 'shop_id'),
      ('public', 'carts', 'status'),
      ('public', 'cart_items_v2', 'id'),
      ('public', 'cart_items_v2', 'cart_id'),
      ('public', 'cart_items_v2', 'shop_product_id'),
      ('public', 'cart_items_v2', 'quantity'),
      ('public', 'qr_sessions', 'id'),
      ('public', 'qr_sessions', 'session_token'),
      ('public', 'qr_sessions', 'user_id'),
      ('public', 'qr_sessions', 'cart_id'),
      ('public', 'qr_sessions', 'shop_id'),
      ('public', 'qr_sessions', 'status'),
      ('public', 'qr_sessions', 'expires_at'),
      ('public', 'qr_sessions', 'used_at')
  ) AS required_columns(schema_name, table_name, column_name)
  WHERE NOT EXISTS (
    SELECT 1
    FROM information_schema.columns AS c
    WHERE c.table_schema = schema_name
      AND c.table_name = table_name
      AND c.column_name = column_name
  );

  IF v_missing_columns IS NOT NULL THEN
    RAISE EXCEPTION
      'Required columns are missing: %. Run the prerequisite migrations first.',
      v_missing_columns
      USING ERRCODE = '42703';
  END IF;
END
$preflight$;

-- Needed for the opaque 256-bit QR token generated by create_qr_session().
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ====================
-- qr_sessions additions
-- ====================
-- These columns remain nullable for historical non-active sessions created by
-- the earlier migration. Every session created by the new RPC fills them.
ALTER TABLE public.qr_sessions
  ADD COLUMN IF NOT EXISTS total_amount NUMERIC;

ALTER TABLE public.qr_sessions
  ADD COLUMN IF NOT EXISTS item_count INTEGER;

ALTER TABLE public.qr_sessions
  ADD COLUMN IF NOT EXISTS confirmed_by_user_id UUID;

DO $constraints$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'qr_sessions_total_amount_nonnegative_check'
      AND conrelid = 'public.qr_sessions'::regclass
  ) THEN
    ALTER TABLE public.qr_sessions
      ADD CONSTRAINT qr_sessions_total_amount_nonnegative_check
      CHECK (total_amount IS NULL OR total_amount >= 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'qr_sessions_item_count_nonnegative_check'
      AND conrelid = 'public.qr_sessions'::regclass
  ) THEN
    ALTER TABLE public.qr_sessions
      ADD CONSTRAINT qr_sessions_item_count_nonnegative_check
      CHECK (item_count IS NULL OR item_count >= 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'qr_sessions_confirmed_by_user_id_fkey'
      AND conrelid = 'public.qr_sessions'::regclass
  ) THEN
    ALTER TABLE public.qr_sessions
      ADD CONSTRAINT qr_sessions_confirmed_by_user_id_fkey
      FOREIGN KEY (confirmed_by_user_id)
      REFERENCES auth.users(id)
      ON DELETE SET NULL;
  END IF;
END
$constraints$;

CREATE INDEX IF NOT EXISTS idx_qr_sessions_confirmed_by_user_id
  ON public.qr_sessions(confirmed_by_user_id);

-- ====================
-- Cart state and write hardening
-- ====================
-- A customer may edit only an active cart and may transition it only to
-- cancelled. Only the trusted confirmation RPC may set checked_out. This
-- keeps a verified cart and its proof from being changed or deleted later.
DO $cart_status_constraint$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'carts_status_check'
      AND conrelid = 'public.carts'::regclass
  ) THEN
    ALTER TABLE public.carts
      ADD CONSTRAINT carts_status_check
      CHECK (status IN ('active', 'checked_out', 'cancelled', 'expired'));
  END IF;
END
$cart_status_constraint$;

DROP POLICY IF EXISTS "Users can create own carts" ON public.carts;
DROP POLICY IF EXISTS "Users can update own carts" ON public.carts;
DROP POLICY IF EXISTS "Users can delete own carts" ON public.carts;

CREATE POLICY "Users can create own carts"
  ON public.carts
  FOR INSERT
  TO authenticated
  WITH CHECK (
    auth.uid() = user_id
    AND status = 'active'
  );

CREATE POLICY "Users can update own carts"
  ON public.carts
  FOR UPDATE
  TO authenticated
  USING (
    auth.uid() = user_id
    AND status = 'active'
  )
  WITH CHECK (
    auth.uid() = user_id
    AND status IN ('active', 'cancelled')
  );

CREATE POLICY "Users can delete own carts"
  ON public.carts
  FOR DELETE
  TO authenticated
  USING (
    auth.uid() = user_id
    AND status IN ('active', 'cancelled')
  );

DROP POLICY IF EXISTS "Users can create own cart items v2"
  ON public.cart_items_v2;
DROP POLICY IF EXISTS "Users can update own cart items v2"
  ON public.cart_items_v2;
DROP POLICY IF EXISTS "Users can delete own cart items v2"
  ON public.cart_items_v2;

CREATE POLICY "Users can create own cart items v2"
  ON public.cart_items_v2
  FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.carts AS c
      JOIN public.shop_products AS sp
        ON sp.id = cart_items_v2.shop_product_id
      WHERE c.id = cart_items_v2.cart_id
        AND c.user_id = auth.uid()
        AND c.status = 'active'
        AND sp.shop_id = c.shop_id
        AND sp.is_active = TRUE
        AND sp.is_available = TRUE
    )
  );

CREATE POLICY "Users can update own cart items v2"
  ON public.cart_items_v2
  FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.carts AS c
      WHERE c.id = cart_items_v2.cart_id
        AND c.user_id = auth.uid()
        AND c.status = 'active'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.carts AS c
      JOIN public.shop_products AS sp
        ON sp.id = cart_items_v2.shop_product_id
      WHERE c.id = cart_items_v2.cart_id
        AND c.user_id = auth.uid()
        AND c.status = 'active'
        AND sp.shop_id = c.shop_id
        AND sp.is_active = TRUE
        AND sp.is_available = TRUE
    )
  );

CREATE POLICY "Users can delete own cart items v2"
  ON public.cart_items_v2
  FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.carts AS c
      WHERE c.id = cart_items_v2.cart_id
        AND c.user_id = auth.uid()
        AND c.status = 'active'
    )
  );

-- Product listings are retired with is_active/is_available instead of being
-- physically deleted while any cart history still references them.
DO $cart_item_shop_product_fk$
DECLARE
  v_constraint_name TEXT;
BEGIN
  FOR v_constraint_name IN
    SELECT c.conname
    FROM pg_constraint AS c
    JOIN pg_attribute AS a
      ON a.attrelid = c.conrelid
     AND a.attnum = ANY (c.conkey)
    WHERE c.contype = 'f'
      AND c.conrelid = 'public.cart_items_v2'::regclass
      AND c.confrelid = 'public.shop_products'::regclass
      AND a.attname = 'shop_product_id'
  LOOP
    EXECUTE format(
      'ALTER TABLE public.cart_items_v2 DROP CONSTRAINT %I',
      v_constraint_name
    );
  END LOOP;

  ALTER TABLE public.cart_items_v2
    ADD CONSTRAINT cart_items_v2_shop_product_id_fkey
    FOREIGN KEY (shop_product_id)
    REFERENCES public.shop_products(id)
    ON DELETE RESTRICT;
END
$cart_item_shop_product_fk$;

-- A shop with commercial history is deactivated, never physically removed by
-- its owner. This prevents the existing CASCADE chain from erasing proof.
DROP POLICY IF EXISTS "Shop owners can delete own shops" ON public.shops;

-- ====================
-- Immutable QR item snapshot
-- ====================
-- shop_product_id is deliberately stored without a foreign key. The snapshot
-- must survive a later shop-product deletion unchanged.
CREATE TABLE IF NOT EXISTS public.qr_session_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  qr_session_id UUID NOT NULL
    REFERENCES public.qr_sessions(id) ON DELETE CASCADE,
  shop_product_id UUID NOT NULL,
  product_name TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  unit_price NUMERIC NOT NULL,
  line_total NUMERIC GENERATED ALWAYS AS (unit_price * quantity) STORED,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT qr_session_items_quantity_positive_check
    CHECK (quantity > 0),
  CONSTRAINT qr_session_items_unit_price_nonnegative_check
    CHECK (unit_price >= 0),
  CONSTRAINT qr_session_items_session_shop_product_unique
    UNIQUE (qr_session_id, shop_product_id)
);

CREATE INDEX IF NOT EXISTS idx_qr_session_items_qr_session_id
  ON public.qr_session_items(qr_session_id);

ALTER TABLE public.qr_session_items ENABLE ROW LEVEL SECURITY;

-- Customers may read only snapshots belonging to their own QR sessions.
-- No merchant-wide table policy is added; merchant verification goes through
-- the two restricted RPC functions below.
DROP POLICY IF EXISTS "Users can read own qr session items"
  ON public.qr_session_items;

CREATE POLICY "Users can read own qr session items"
  ON public.qr_session_items
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.qr_sessions AS qs
      WHERE qs.id = qr_session_items.qr_session_id
        AND qs.user_id = auth.uid()
    )
  );

REVOKE ALL PRIVILEGES ON TABLE public.qr_session_items
  FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.qr_session_items TO authenticated;

-- ====================
-- Permanent verified purchase proof
-- ====================
-- These records deliberately store UUID snapshots without foreign keys to
-- users, shops, carts, or QR sessions. Account/shop cleanup must not erase an
-- already verified purchase. No client receives write access.
CREATE TABLE IF NOT EXISTS public.verified_transactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  source_qr_session_id UUID NOT NULL UNIQUE,
  customer_user_id UUID NOT NULL,
  shop_id UUID NOT NULL,
  shop_name TEXT NOT NULL,
  confirmed_by_user_id UUID NOT NULL,
  item_count INTEGER NOT NULL,
  total_amount NUMERIC NOT NULL,
  confirmed_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT verified_transactions_item_count_positive_check
    CHECK (item_count > 0),
  CONSTRAINT verified_transactions_total_amount_nonnegative_check
    CHECK (total_amount >= 0)
);

CREATE TABLE IF NOT EXISTS public.verified_transaction_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  verified_transaction_id UUID NOT NULL
    REFERENCES public.verified_transactions(id) ON DELETE CASCADE,
  shop_product_id UUID NOT NULL,
  product_name TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  unit_price NUMERIC NOT NULL,
  line_total NUMERIC NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT verified_transaction_items_quantity_positive_check
    CHECK (quantity > 0),
  CONSTRAINT verified_transaction_items_unit_price_nonnegative_check
    CHECK (unit_price >= 0),
  CONSTRAINT verified_transaction_items_line_total_nonnegative_check
    CHECK (line_total >= 0),
  CONSTRAINT verified_transaction_items_source_item_unique
    UNIQUE (verified_transaction_id, shop_product_id)
);

CREATE INDEX IF NOT EXISTS idx_verified_transactions_customer_user_id
  ON public.verified_transactions(customer_user_id);
CREATE INDEX IF NOT EXISTS idx_verified_transactions_shop_id
  ON public.verified_transactions(shop_id);
CREATE INDEX IF NOT EXISTS idx_verified_transactions_confirmed_by_user_id
  ON public.verified_transactions(confirmed_by_user_id);
CREATE INDEX IF NOT EXISTS idx_verified_transactions_confirmed_at
  ON public.verified_transactions(confirmed_at DESC);
CREATE INDEX IF NOT EXISTS idx_verified_transaction_items_transaction_id
  ON public.verified_transaction_items(verified_transaction_id);

ALTER TABLE public.verified_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.verified_transaction_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Participants can read verified transactions"
  ON public.verified_transactions;
CREATE POLICY "Participants can read verified transactions"
  ON public.verified_transactions
  FOR SELECT
  TO authenticated
  USING (
    customer_user_id = auth.uid()
    OR confirmed_by_user_id = auth.uid()
  );

DROP POLICY IF EXISTS "Participants can read verified transaction items"
  ON public.verified_transaction_items;
CREATE POLICY "Participants can read verified transaction items"
  ON public.verified_transaction_items
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.verified_transactions AS vt
      WHERE vt.id = verified_transaction_items.verified_transaction_id
        AND (
          vt.customer_user_id = auth.uid()
          OR vt.confirmed_by_user_id = auth.uid()
        )
    )
  );

REVOKE ALL PRIVILEGES ON TABLE public.verified_transactions
  FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.verified_transaction_items
  FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.verified_transactions TO authenticated;
GRANT SELECT ON TABLE public.verified_transaction_items TO authenticated;

-- ====================
-- Invalidate unverifiable legacy active sessions
-- ====================
UPDATE public.qr_sessions AS qs
SET status = 'cancelled'
WHERE qs.status = 'active'
  AND NOT EXISTS (
    SELECT 1
    FROM public.qr_session_items AS qsi
    WHERE qsi.qr_session_id = qs.id
  );

-- A failed/partial earlier deployment must not silently choose between two
-- valid snapshots. Stop with an actionable error instead.
DO $duplicates$
DECLARE
  v_duplicate_carts TEXT;
BEGIN
  SELECT string_agg(cart_id::TEXT, ', ' ORDER BY cart_id::TEXT)
    INTO v_duplicate_carts
  FROM (
    SELECT cart_id
    FROM public.qr_sessions
    WHERE status = 'active'
    GROUP BY cart_id
    HAVING COUNT(*) > 1
  ) AS duplicate_rows;

  IF v_duplicate_carts IS NOT NULL THEN
    RAISE EXCEPTION
      'More than one active snapshotted QR exists for cart(s): %. Resolve these rows manually before retrying.',
      v_duplicate_carts
      USING ERRCODE = '23505';
  END IF;
END
$duplicates$;

CREATE UNIQUE INDEX IF NOT EXISTS qr_sessions_one_active_per_cart_idx
  ON public.qr_sessions(cart_id)
  WHERE status = 'active';

-- ====================
-- Cart-change invalidation triggers
-- ====================
-- The BEFORE trigger reacts only to fields represented by the snapshot. It
-- takes the same parent-cart lock used by QR creation before the item mutation
-- becomes visible, so creation sees either the complete old or complete new
-- cart and a waiting edit always cancels the earlier snapshot.
CREATE OR REPLACE FUNCTION public.cancel_active_qr_after_cart_item_change()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, extensions, auth
AS $function$
DECLARE
  v_old_cart_id UUID;
  v_new_cart_id UUID;
BEGIN
  IF TG_OP = 'UPDATE'
     AND OLD.cart_id IS NOT DISTINCT FROM NEW.cart_id
     AND OLD.shop_product_id IS NOT DISTINCT FROM NEW.shop_product_id
     AND OLD.quantity IS NOT DISTINCT FROM NEW.quantity THEN
    RETURN NEW;
  END IF;

  IF TG_OP IN ('UPDATE', 'DELETE') THEN
    v_old_cart_id := OLD.cart_id;
  END IF;

  IF TG_OP IN ('INSERT', 'UPDATE') THEN
    v_new_cart_id := NEW.cart_id;
  END IF;

  PERFORM c.id
  FROM public.carts AS c
  WHERE c.id = ANY (
    array_remove(ARRAY[v_old_cart_id, v_new_cart_id]::UUID[], NULL)
  )
  ORDER BY c.id
  FOR UPDATE;

  IF EXISTS (
    SELECT 1
    FROM public.carts AS c
    WHERE c.id = ANY (
      array_remove(ARRAY[v_old_cart_id, v_new_cart_id]::UUID[], NULL)
    )
      AND c.status <> 'active'
  ) THEN
    RAISE EXCEPTION 'Cart is no longer active'
      USING ERRCODE = '55000';
  END IF;

  UPDATE public.qr_sessions AS qs
  SET status = 'cancelled'
  WHERE qs.status = 'active'
    AND qs.cart_id = ANY (
      array_remove(ARRAY[v_old_cart_id, v_new_cart_id]::UUID[], NULL)
    );

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;

  RETURN NEW;
END;
$function$;

REVOKE ALL ON FUNCTION public.cancel_active_qr_after_cart_item_change()
  FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS trg_cancel_active_qr_after_cart_item_change
  ON public.cart_items_v2;

CREATE TRIGGER trg_cancel_active_qr_after_cart_item_change
  BEFORE INSERT OR UPDATE OR DELETE ON public.cart_items_v2
  FOR EACH ROW
  EXECUTE FUNCTION public.cancel_active_qr_after_cart_item_change();

CREATE OR REPLACE FUNCTION public.cancel_active_qr_after_cart_change()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, extensions, auth
AS $function$
BEGIN
  IF OLD.user_id IS NOT DISTINCT FROM NEW.user_id
     AND OLD.shop_id IS NOT DISTINCT FROM NEW.shop_id
     AND OLD.status IS NOT DISTINCT FROM NEW.status THEN
    RETURN NEW;
  END IF;

  UPDATE public.qr_sessions AS qs
  SET status = 'cancelled'
  WHERE qs.cart_id = NEW.id
    AND qs.status = 'active';

  RETURN NEW;
END;
$function$;

REVOKE ALL ON FUNCTION public.cancel_active_qr_after_cart_change()
  FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS trg_cancel_active_qr_after_cart_change
  ON public.carts;

CREATE TRIGGER trg_cancel_active_qr_after_cart_change
  AFTER UPDATE OF user_id, shop_id, status ON public.carts
  FOR EACH ROW
  EXECUTE FUNCTION public.cancel_active_qr_after_cart_change();

-- ====================
-- Customer RPC: create a locked, immutable QR snapshot
-- ====================
CREATE OR REPLACE FUNCTION public.create_qr_session(p_cart_id UUID)
RETURNS public.qr_sessions
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, extensions, auth
AS $function$
DECLARE
  v_user_id UUID;
  v_now TIMESTAMPTZ := clock_timestamp();
  v_cart public.carts%ROWTYPE;
  v_session public.qr_sessions%ROWTYPE;
  v_cart_line_count INTEGER;
  v_snapshot_line_count INTEGER;
  v_snapshot_item_count INTEGER;
  v_snapshot_total NUMERIC;
BEGIN
  v_user_id := auth.uid();

  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required'
      USING ERRCODE = '28000';
  END IF;

  -- This row lock is the serialization point shared with cart-change triggers
  -- and confirmation. Concurrent create calls for one cart cannot diverge.
  SELECT c.*
    INTO v_cart
  FROM public.carts AS c
  WHERE c.id = p_cart_id
    AND c.user_id = v_user_id
    AND c.status = 'active'
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Active cart not found'
      USING ERRCODE = 'P0002';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.shops AS s
    WHERE s.id = v_cart.shop_id
      AND s.is_active = TRUE
  ) THEN
    RAISE EXCEPTION 'Shop is not active'
      USING ERRCODE = '55000';
  END IF;

  -- Every cart-item mutation takes this same parent-cart lock in its BEFORE
  -- trigger. The following reads therefore describe one stable cart version.
  SELECT COUNT(*)::INTEGER
    INTO v_cart_line_count
  FROM public.cart_items_v2 AS ci
  WHERE ci.cart_id = v_cart.id;

  IF v_cart_line_count = 0 THEN
    RAISE EXCEPTION 'Cannot create QR session for an empty cart'
      USING ERRCODE = 'P0001';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.cart_items_v2 AS ci
    JOIN public.shop_products AS sp ON sp.id = ci.shop_product_id
    WHERE ci.cart_id = v_cart.id
      AND (
        sp.shop_id IS DISTINCT FROM v_cart.shop_id
        OR sp.is_active IS NOT TRUE
        OR sp.is_available IS NOT TRUE
        OR sp.price IS NULL
        OR sp.price < 0
      )
  ) THEN
    RAISE EXCEPTION 'Cart contains an unavailable or different shop item'
      USING ERRCODE = '23514';
  END IF;

  UPDATE public.qr_sessions AS qs
  SET status = 'expired'
  WHERE qs.cart_id = v_cart.id
    AND qs.user_id = v_user_id
    AND qs.status = 'active'
    AND qs.expires_at <= v_now;

  SELECT qs.*
    INTO v_session
  FROM public.qr_sessions AS qs
  WHERE qs.cart_id = v_cart.id
    AND qs.user_id = v_user_id
    AND qs.status = 'active'
    AND qs.expires_at > v_now
  LIMIT 1
  FOR UPDATE;

  IF FOUND THEN
    SELECT
      COUNT(*)::INTEGER,
      COALESCE(SUM(qsi.quantity), 0)::INTEGER,
      COALESCE(SUM(qsi.line_total), 0)
      INTO
        v_snapshot_line_count,
        v_snapshot_item_count,
        v_snapshot_total
    FROM public.qr_session_items AS qsi
    WHERE qsi.qr_session_id = v_session.id;

    IF v_snapshot_line_count > 0
       AND v_session.item_count = v_snapshot_item_count
       AND v_session.total_amount = v_snapshot_total THEN
      RETURN v_session;
    END IF;

    -- Never reuse an incomplete or internally inconsistent active snapshot.
    UPDATE public.qr_sessions
    SET status = 'cancelled'
    WHERE id = v_session.id;
  END IF;

  INSERT INTO public.qr_sessions (
    session_token,
    user_id,
    cart_id,
    shop_id,
    status,
    expires_at,
    used_at,
    total_amount,
    item_count,
    confirmed_by_user_id
  )
  VALUES (
    encode(gen_random_bytes(32), 'hex'),
    v_user_id,
    v_cart.id,
    v_cart.shop_id,
    'active',
    v_now + interval '2 minutes',
    NULL,
    0,
    0,
    NULL
  )
  RETURNING * INTO v_session;

  INSERT INTO public.qr_session_items (
    qr_session_id,
    shop_product_id,
    product_name,
    quantity,
    unit_price
  )
  SELECT
    v_session.id,
    sp.id,
    p.name,
    ci.quantity,
    sp.price
  FROM public.cart_items_v2 AS ci
  JOIN public.shop_products AS sp
    ON sp.id = ci.shop_product_id
   AND sp.shop_id = v_cart.shop_id
  JOIN public.products AS p ON p.id = sp.product_id
  WHERE ci.cart_id = v_cart.id
  ORDER BY ci.id;

  GET DIAGNOSTICS v_snapshot_line_count = ROW_COUNT;

  IF v_snapshot_line_count <> v_cart_line_count THEN
    RAISE EXCEPTION
      'Cart snapshot is incomplete (% of % lines copied)',
      v_snapshot_line_count,
      v_cart_line_count
      USING ERRCODE = 'P0001';
  END IF;

  SELECT
    COALESCE(SUM(qsi.quantity), 0)::INTEGER,
    COALESCE(SUM(qsi.line_total), 0)
    INTO v_snapshot_item_count, v_snapshot_total
  FROM public.qr_session_items AS qsi
  WHERE qsi.qr_session_id = v_session.id;

  UPDATE public.qr_sessions
  SET item_count = v_snapshot_item_count,
      total_amount = v_snapshot_total
  WHERE id = v_session.id
  RETURNING * INTO v_session;

  RETURN v_session;
END;
$function$;

REVOKE ALL ON FUNCTION public.create_qr_session(UUID)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.create_qr_session(UUID) TO authenticated;

-- ====================
-- Merchant RPC: inspect a QR belonging to the caller's own shop
-- ====================
CREATE OR REPLACE FUNCTION public.get_qr_session_for_verification(
  p_session_token TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, extensions, auth
AS $function$
DECLARE
  v_user_id UUID := auth.uid();
  v_now TIMESTAMPTZ := clock_timestamp();
  v_payload JSONB;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required'
      USING ERRCODE = '28000';
  END IF;

  IF p_session_token IS NULL OR btrim(p_session_token) = '' THEN
    RAISE EXCEPTION 'QR session token is required'
      USING ERRCODE = '22023';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.profiles AS p
    WHERE p.id = v_user_id
      AND p.role IN ('merchant', 'admin')
  ) THEN
    RAISE EXCEPTION 'Merchant access required'
      USING ERRCODE = '42501';
  END IF;

  -- Expiry is persisted only after the caller has proven shop ownership.
  UPDATE public.qr_sessions AS qs
  SET status = 'expired'
  WHERE qs.session_token = p_session_token
    AND qs.status = 'active'
    AND qs.expires_at <= v_now
    AND EXISTS (
      SELECT 1
      FROM public.shops AS owned_shop
      WHERE owned_shop.id = qs.shop_id
        AND owned_shop.owner_user_id = v_user_id
        AND owned_shop.is_active = TRUE
    );

  SELECT jsonb_build_object(
           'session_id', qs.id,
           'session_token', qs.session_token,
           'status', qs.status,
           'expires_at', qs.expires_at,
           'used_at', qs.used_at,
           'shop_id', qs.shop_id,
           'shop_name', s.name,
           'item_count', qs.item_count,
           'total_amount', qs.total_amount,
           'items', COALESCE(
             (
               SELECT jsonb_agg(
                        jsonb_build_object(
                          'id', qsi.id,
                          'shop_product_id', qsi.shop_product_id,
                          'product_name', qsi.product_name,
                          'quantity', qsi.quantity,
                          'unit_price', qsi.unit_price,
                          'line_total', qsi.line_total
                        )
                        ORDER BY qsi.created_at, qsi.id
                      )
               FROM public.qr_session_items AS qsi
               WHERE qsi.qr_session_id = qs.id
             ),
             '[]'::JSONB
           )
         )
    INTO v_payload
  FROM public.qr_sessions AS qs
  JOIN public.shops AS s
    ON s.id = qs.shop_id
   AND s.owner_user_id = v_user_id
   AND s.is_active = TRUE
  WHERE qs.session_token = p_session_token;

  IF v_payload IS NULL THEN
    RAISE EXCEPTION 'QR session not found for this shop'
      USING ERRCODE = 'P0002';
  END IF;

  RETURN v_payload;
END;
$function$;

REVOKE ALL ON FUNCTION public.get_qr_session_for_verification(TEXT)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_qr_session_for_verification(TEXT)
  TO authenticated;

-- ====================
-- Merchant RPC: one-time atomic confirmation
-- ====================
CREATE OR REPLACE FUNCTION public.confirm_qr_session(p_session_token TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, extensions, auth
AS $function$
DECLARE
  v_user_id UUID := auth.uid();
  v_now TIMESTAMPTZ := clock_timestamp();
  v_session_id UUID;
  v_cart_id UUID;
  v_cart public.carts%ROWTYPE;
  v_session public.qr_sessions%ROWTYPE;
  v_snapshot_line_count INTEGER;
  v_snapshot_item_count INTEGER;
  v_snapshot_total NUMERIC;
  v_verified_transaction_id UUID;
  v_verified_item_count INTEGER;
  v_payload JSONB;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required'
      USING ERRCODE = '28000';
  END IF;

  IF p_session_token IS NULL OR btrim(p_session_token) = '' THEN
    RAISE EXCEPTION 'QR session token is required'
      USING ERRCODE = '22023';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.profiles AS p
    WHERE p.id = v_user_id
      AND p.role IN ('merchant', 'admin')
  ) THEN
    RAISE EXCEPTION 'Merchant access required'
      USING ERRCODE = '42501';
  END IF;

  -- Resolve only a session owned by this caller's shop. This first read is a
  -- lock-order hint; all authorization and state are checked again after locks.
  SELECT qs.id, qs.cart_id
    INTO v_session_id, v_cart_id
  FROM public.qr_sessions AS qs
  JOIN public.shops AS s
    ON s.id = qs.shop_id
   AND s.owner_user_id = v_user_id
   AND s.is_active = TRUE
  WHERE qs.session_token = p_session_token;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'QR session not found for this shop'
      USING ERRCODE = 'P0002';
  END IF;

  -- Keep the confirmation/creation lock order cart -> session. Item-change
  -- invalidation never takes these locks in reverse order, so two confirmations
  -- cannot both succeed and cart edits cannot deadlock this transaction.
  SELECT c.*
    INTO v_cart
  FROM public.carts AS c
  WHERE c.id = v_cart_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Cart not found for QR session'
      USING ERRCODE = 'P0002';
  END IF;

  SELECT qs.*
    INTO v_session
  FROM public.qr_sessions AS qs
  WHERE qs.id = v_session_id
    AND qs.cart_id = v_cart.id
    AND qs.session_token = p_session_token
    AND EXISTS (
      SELECT 1
      FROM public.shops AS owned_shop
      WHERE owned_shop.id = qs.shop_id
        AND owned_shop.owner_user_id = v_user_id
        AND owned_shop.is_active = TRUE
    )
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'QR session not found for this shop'
      USING ERRCODE = 'P0002';
  END IF;

  IF v_session.status = 'used'
     OR v_session.used_at IS NOT NULL
     OR v_session.confirmed_by_user_id IS NOT NULL THEN
    RAISE EXCEPTION 'QR session has already been confirmed'
      USING ERRCODE = '55000';
  END IF;

  IF v_session.status <> 'active' THEN
    RAISE EXCEPTION 'QR session is not active'
      USING ERRCODE = '55000';
  END IF;

  IF v_session.expires_at <= v_now THEN
    RAISE EXCEPTION 'QR session has expired'
      USING ERRCODE = '55000';
  END IF;

  IF v_cart.status <> 'active'
     OR v_cart.user_id IS DISTINCT FROM v_session.user_id
     OR v_cart.shop_id IS DISTINCT FROM v_session.shop_id THEN
    RAISE EXCEPTION 'Cart is no longer eligible for confirmation'
      USING ERRCODE = '55000';
  END IF;

  SELECT
    COUNT(*)::INTEGER,
    COALESCE(SUM(qsi.quantity), 0)::INTEGER,
    COALESCE(SUM(qsi.line_total), 0)
    INTO
      v_snapshot_line_count,
      v_snapshot_item_count,
      v_snapshot_total
  FROM public.qr_session_items AS qsi
  WHERE qsi.qr_session_id = v_session.id;

  IF v_snapshot_line_count = 0
     OR v_session.item_count IS DISTINCT FROM v_snapshot_item_count
     OR v_session.total_amount IS DISTINCT FROM v_snapshot_total THEN
    RAISE EXCEPTION 'QR session snapshot is missing or inconsistent'
      USING ERRCODE = '55000';
  END IF;

  INSERT INTO public.verified_transactions (
    source_qr_session_id,
    customer_user_id,
    shop_id,
    shop_name,
    confirmed_by_user_id,
    item_count,
    total_amount,
    confirmed_at
  )
  SELECT
    v_session.id,
    v_session.user_id,
    v_session.shop_id,
    s.name,
    v_user_id,
    v_session.item_count,
    v_session.total_amount,
    v_now
  FROM public.shops AS s
  WHERE s.id = v_session.shop_id
    AND s.owner_user_id = v_user_id
    AND s.is_active = TRUE
  RETURNING id INTO v_verified_transaction_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Verified transaction could not be created'
      USING ERRCODE = '55000';
  END IF;

  INSERT INTO public.verified_transaction_items (
    verified_transaction_id,
    shop_product_id,
    product_name,
    quantity,
    unit_price,
    line_total
  )
  SELECT
    v_verified_transaction_id,
    qsi.shop_product_id,
    qsi.product_name,
    qsi.quantity,
    qsi.unit_price,
    qsi.line_total
  FROM public.qr_session_items AS qsi
  WHERE qsi.qr_session_id = v_session.id
  ORDER BY qsi.created_at, qsi.id;

  GET DIAGNOSTICS v_verified_item_count = ROW_COUNT;

  IF v_verified_item_count <> v_snapshot_line_count THEN
    RAISE EXCEPTION 'Verified transaction item copy is incomplete'
      USING ERRCODE = '55000';
  END IF;

  UPDATE public.qr_sessions
  SET status = 'used',
      used_at = v_now,
      confirmed_by_user_id = v_user_id
  WHERE id = v_session.id
    AND status = 'active'
  RETURNING * INTO v_session;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'QR session could not be confirmed'
      USING ERRCODE = '55000';
  END IF;

  UPDATE public.carts
  SET status = 'checked_out'
  WHERE id = v_cart.id
    AND status = 'active'
    AND user_id = v_session.user_id
    AND shop_id = v_session.shop_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Cart could not be checked out'
      USING ERRCODE = '55000';
  END IF;

  SELECT jsonb_build_object(
           'session_id', qs.id,
           'session_token', qs.session_token,
           'status', qs.status,
           'expires_at', qs.expires_at,
           'used_at', qs.used_at,
           'shop_id', qs.shop_id,
           'shop_name', s.name,
           'item_count', qs.item_count,
           'total_amount', qs.total_amount,
           'items', COALESCE(
             (
               SELECT jsonb_agg(
                        jsonb_build_object(
                          'id', qsi.id,
                          'shop_product_id', qsi.shop_product_id,
                          'product_name', qsi.product_name,
                          'quantity', qsi.quantity,
                          'unit_price', qsi.unit_price,
                          'line_total', qsi.line_total
                        )
                        ORDER BY qsi.created_at, qsi.id
                      )
               FROM public.qr_session_items AS qsi
               WHERE qsi.qr_session_id = qs.id
             ),
             '[]'::JSONB
           )
         )
    INTO v_payload
  FROM public.qr_sessions AS qs
  JOIN public.shops AS s ON s.id = qs.shop_id
  WHERE qs.id = v_session.id;

  RETURN v_payload;
END;
$function$;

REVOKE ALL ON FUNCTION public.confirm_qr_session(TEXT)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.confirm_qr_session(TEXT) TO authenticated;

COMMIT;

-- ====================
-- Manual verification queries (read-only)
-- ====================
-- 1. New qr_sessions columns:
-- SELECT column_name, data_type, is_nullable
-- FROM information_schema.columns
-- WHERE table_schema = 'public'
--   AND table_name = 'qr_sessions'
--   AND column_name IN (
--     'total_amount', 'item_count', 'confirmed_by_user_id'
--   )
-- ORDER BY column_name;
--
-- 2. Snapshot table and RLS:
-- SELECT to_regclass('public.qr_session_items') AS snapshot_table;
-- SELECT relrowsecurity
-- FROM pg_class
-- WHERE oid = 'public.qr_session_items'::regclass;
--
-- 3. Snapshot SELECT policy (there must be no client write policy):
-- SELECT policyname, cmd, roles, qual, with_check
-- FROM pg_policies
-- WHERE schemaname = 'public'
--   AND tablename = 'qr_session_items'
-- ORDER BY policyname;
--
-- 4. At most one active QR per cart:
-- SELECT indexname, indexdef
-- FROM pg_indexes
-- WHERE schemaname = 'public'
--   AND tablename = 'qr_sessions'
--   AND indexname = 'qr_sessions_one_active_per_cart_idx';
--
-- SELECT cart_id, COUNT(*) AS active_count
-- FROM public.qr_sessions
-- WHERE status = 'active'
-- GROUP BY cart_id
-- HAVING COUNT(*) > 1;
--
-- 5. No active session may be snapshot-less:
-- SELECT qs.id, qs.cart_id
-- FROM public.qr_sessions AS qs
-- WHERE qs.status = 'active'
--   AND NOT EXISTS (
--     SELECT 1
--     FROM public.qr_session_items AS qsi
--     WHERE qsi.qr_session_id = qs.id
--   );
--
-- 6. Stored totals must match immutable snapshot totals:
-- SELECT
--   qs.id,
--   qs.item_count,
--   SUM(qsi.quantity) AS calculated_item_count,
--   qs.total_amount,
--   SUM(qsi.line_total) AS calculated_total_amount
-- FROM public.qr_sessions AS qs
-- JOIN public.qr_session_items AS qsi ON qsi.qr_session_id = qs.id
-- GROUP BY qs.id
-- HAVING qs.item_count IS DISTINCT FROM SUM(qsi.quantity)::INTEGER
--    OR qs.total_amount IS DISTINCT FROM SUM(qsi.line_total);
--
-- 7. RPC security and execute grants:
-- SELECT
--   p.proname,
--   p.prosecdef AS security_definer,
--   p.proconfig,
--   has_function_privilege(
--     'anon',
--     p.oid,
--     'EXECUTE'
--   ) AS anon_can_execute,
--   has_function_privilege(
--     'authenticated',
--     p.oid,
--     'EXECUTE'
--   ) AS authenticated_can_execute
-- FROM pg_proc AS p
-- JOIN pg_namespace AS n ON n.oid = p.pronamespace
-- WHERE n.nspname = 'public'
--   AND p.proname IN (
--     'create_qr_session',
--     'get_qr_session_for_verification',
--     'confirm_qr_session'
--   )
-- ORDER BY p.proname;
--
-- 8. Invalidation triggers:
-- SELECT event_object_table, trigger_name, action_timing, event_manipulation
-- FROM information_schema.triggers
-- WHERE trigger_schema = 'public'
--   AND trigger_name IN (
--     'trg_cancel_active_qr_after_cart_item_change',
--     'trg_cancel_active_qr_after_cart_change'
--   )
-- ORDER BY event_object_table, trigger_name, event_manipulation;
--
-- 9. Permanent verified purchase proof tables and RLS:
-- SELECT to_regclass('public.verified_transactions') AS transactions_table,
--        to_regclass('public.verified_transaction_items') AS items_table;
-- SELECT relname, relrowsecurity
-- FROM pg_class
-- WHERE oid IN (
--   'public.verified_transactions'::regclass,
--   'public.verified_transaction_items'::regclass
-- );
--
-- 10. Merchant shop deletion is disabled; shops are deactivated instead:
-- SELECT policyname, cmd
-- FROM pg_policies
-- WHERE schemaname = 'public'
--   AND tablename = 'shops'
--   AND cmd = 'DELETE';
--
-- 11. shop_product deletion cannot cascade through cart history:
-- SELECT conname, confdeltype, pg_get_constraintdef(oid)
-- FROM pg_constraint
-- WHERE conrelid = 'public.cart_items_v2'::regclass
--   AND confrelid = 'public.shop_products'::regclass;
