import {check,uuid,read,rollbackPath,functions,literal,identifier,version,name,payload,hash,stable,safeError} from './common.mjs';
import {identity} from '../../production_taxonomy/execution/validators.mjs';
import {ledger,legacyDataHashes} from '../../production_taxonomy/execution/catalog.mjs';
import {canonicalData,unchanged0012Catalog} from '../execution/catalog.mjs';
import {baseline} from '../execution/validators.mjs';
import {transaction} from './transaction.mjs';
import {verify} from './seal.mjs';
export async function connection(ctx){
 if(ctx.db.closed){check(typeof ctx.reconnect==='function','RECONNECT_REQUIRED_FOR_CONTAINMENT');ctx.db=await ctx.reconnect();}
 await identity(ctx.db);return ctx.db;
}
const signatures=()=>[...read(rollbackPath).matchAll(/^DROP FUNCTION (public\.[a-z0-9_]+\([^;]+\)) RESTRICT;$/gm)].map(m=>m[1].toLowerCase());
async function objects(db){
 const funcs=(await db.query("SELECT oid::text,proname,oid::regprocedure::text AS signature,pg_get_userbyid(proowner) AS owner FROM pg_proc WHERE pronamespace='public'::regnamespace AND proname=ANY($1::text[]) ORDER BY proname,oid",[functions])).rows;
 const expected=[];for(const sig of signatures()){const row=(await db.query('SELECT to_regprocedure($1)::oid::text AS oid',[sig])).rows[0];if(row.oid)expected.push(row.oid);}
 const schemas=(await db.query("SELECT pg_get_userbyid(nspowner) AS owner FROM pg_namespace WHERE nspname='production_preview_private'")).rows;
 const tables=(await db.query("SELECT c.relname,c.relkind::text,pg_get_userbyid(c.relowner) AS owner FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='production_preview_private' AND c.relkind IN ('r','p','v','m','S') ORDER BY c.relname")).rows;
 return {funcs,expected,schemas,tables};
}
async function privateTableSafe(db){
 const present=(await db.query("SELECT to_regclass('production_preview_private.testers') IS NOT NULL AS present")).rows[0].present;if(!present)return false;
 const rows=(await db.query("SELECT c.relkind::text,pg_get_userbyid(c.relowner) AS owner,(SELECT count(*)::int FROM pg_trigger WHERE tgrelid=c.oid AND NOT tgisinternal) AS triggers FROM pg_class c WHERE c.oid='production_preview_private.testers'::regclass")).rows;
 const cols=(await db.query("SELECT attname,atttypid::regtype::text AS type FROM pg_attribute WHERE attrelid='production_preview_private.testers'::regclass AND attnum>0 AND NOT attisdropped ORDER BY attnum")).rows;
 check(rows.length===1&&rows[0].owner==='postgres'&&rows[0].relkind==='r'&&rows[0].triggers===0,'ALLOWLIST_STRUCTURAL_SAFETY');
 check(stable(cols)===stable([{attname:'user_id',type:'uuid'},{attname:'enabled',type:'boolean'},{attname:'granted_at',type:'timestamp with time zone'},{attname:'expires_at',type:'timestamp with time zone'}]),'ALLOWLIST_COLUMN_SAFETY');return true;
}
export async function removeTester(ctx,packageHash,uid){
 verify(packageHash);check(uuid(uid),'EXACT_RUNTIME_UID_REQUIRED');const db=await connection(ctx);
 return transaction(db,async()=>{
  if(!await privateTableSafe(db))return {result:'PASS',removed:0,remaining_for_subject:0};
  const before=(await db.query('SELECT count(*)::int AS n FROM production_preview_private.testers WHERE user_id=$1::uuid',[uid])).rows[0].n;
  await db.exec(`DELETE FROM production_preview_private.testers WHERE user_id=${literal(uid)}::uuid;`);
  check((await db.query('SELECT count(*)::int AS n FROM production_preview_private.testers WHERE user_id=$1::uuid',[uid])).rows[0].n===0,'SUBJECT_REMOVAL_NOT_EFFECTIVE');
  return {result:'PASS',removed:before,remaining_for_subject:0};
 },{write:true});
}
async function revokeExposure(ctx){
 const db=await connection(ctx);
 return transaction(db,async()=>{
  const state=await objects(db);
  for(const fn of state.funcs){
   check(fn.owner==='postgres','BRIDGE_FUNCTION_OWNER_CHANGED');
   // regprocedure rendering is generated by PostgreSQL, never user SQL.
   // CASCADE here removes dependent EXECUTE grants only; never schema objects.
   const recipients=(await db.query('SELECT DISTINCT CASE WHEN a.grantee=0 THEN NULL ELSE pg_get_userbyid(a.grantee) END AS role FROM pg_proc p CROSS JOIN LATERAL aclexplode(coalesce(p.proacl,acldefault(\'f\',p.proowner))) a WHERE p.oid=$1::oid AND a.grantee<>p.proowner',[fn.oid])).rows;
   const roles=new Set(['PUBLIC','anon','authenticated','service_role',...recipients.map(r=>r.role??'PUBLIC')]);
   await db.exec(`REVOKE ALL PRIVILEGES ON FUNCTION ${fn.signature} FROM ${[...roles].map(r=>r==='PUBLIC'?'PUBLIC':identifier(r)).join(',')} CASCADE;`);
  }
  const exposed=(await db.query("SELECT count(*)::int AS n FROM pg_proc p CROSS JOIN (VALUES ('anon'),('authenticated'),('service_role')) r(role) WHERE p.pronamespace='public'::regnamespace AND p.proname=ANY($1::text[]) AND has_function_privilege(r.role,p.oid,'EXECUTE')",[functions])).rows[0].n;
  check(exposed===0,'PREVIEW_EXECUTE_STILL_EXPOSED');return {result:'PASS',functions_revoked:state.funcs.length,client_execute_exposure:0};
 },{write:true});
}
async function observedCore(db){
 const data={};
 // Snapshot the OBSERVED core, including absent tables or changed columns.
 // A missing legacy table is a failure trigger, not a reason to keep preview.
 for(const table of ['categories','products','shop_products','shops','brands','canonical_categories','canonical_category_qualification','taxonomy_aliases','taxonomy_alias_targets','taxonomy_id_allocations','taxonomy_import_runs','taxonomy_node_relationships','production_taxonomy_config','product_canonical_assignments']){
  const present=(await db.query('SELECT to_regclass($1) IS NOT NULL AS present',['public.'+table])).rows[0].present;
  data[table]=present?hash(stable((await db.query(`SELECT to_jsonb(t) AS row FROM public.${table} t ORDER BY to_jsonb(t)::text COLLATE "C"`)).rows)):'ABSENT';
 }
 return {public_schema:await unchanged0012Catalog(db),data,ledger:(await ledger(db)).filter(r=>r.version!==version)};
}
export async function containAndRollback(ctx,packageHash,uid){
 verify(packageHash);check(uuid(uid),'EXACT_RUNTIME_UID_REQUIRED');
 const result={result:'EMERGENCY_CONTAINMENT',removal:null,exposure:null,bridge_removed:false,core_repaired:false,errors:[]};
 // Separate durable containment commits. A later teardown failure CANNOT undo
 // UID removal or EXECUTE revocation. No full baseline gate precedes them.
 try{result.removal=await removeTester(ctx,packageHash,uid);}catch(e){result.errors.push(safeError(e));}
 try{result.exposure=await revokeExposure(ctx);}catch(e){result.errors.push(safeError(e));}
 if(result.exposure?.client_execute_exposure!==0){result.result='CONTAINMENT_FAILED';return result;}
 result.preview_access_disabled=true;
 try{
  const db=await connection(ctx);
  const teardown=await transaction(db,async()=>{
   const state=await objects(db);
   check(state.funcs.every(f=>f.owner==='postgres'&&state.expected.includes(f.oid)),'EXACT_BRIDGE_SIGNATURES_REQUIRED');
   check(state.schemas.every(s=>s.owner==='postgres')&&state.tables.every(t=>t.relname==='testers'&&t.relkind==='r'&&t.owner==='postgres'),'EXACT_BRIDGE_NAMESPACE_REQUIRED');
   if(state.tables.length)await privateTableSafe(db);
   const entries=(await db.query('SELECT name,statements FROM supabase_migrations.schema_migrations WHERE version=$1',[version])).rows;
   const exactEntry=entries.length===1&&entries[0].name===name&&entries[0].statements?.length===1&&hash(entries[0].statements[0])===payload().sha256;
   const intactFootprint=state.funcs.length===15&&state.expected.length===15&&state.tables.length===1&&state.schemas.length===1;
   const absent=state.funcs.length===0&&state.tables.length===0&&state.schemas.length===0;
   check(entries.length<=1&&(exactEntry||intactFootprint||absent&&entries.length===0),'BRIDGE_PROVENANCE_AMBIGUOUS');
   const core=await observedCore(db);
   for(const sig of signatures())await db.exec(`DROP FUNCTION IF EXISTS ${sig} RESTRICT;`);
   await db.exec('DROP TABLE IF EXISTS production_preview_private.testers RESTRICT; DROP SCHEMA IF EXISTS production_preview_private RESTRICT;');
   await db.exec(`DELETE FROM supabase_migrations.schema_migrations WHERE version=${literal(version)};`);
   check(stable(await observedCore(db))===stable(core),'TEARDOWN_CHANGED_CORE_STATE');
   return {result:'PASS',bridge_removed:true,observed_core_preserved:true,ledger_reconciled:true,already_absent:absent};
  },{write:true});
  Object.assign(result,teardown);result.result='ROLLED_BACK';
 }catch(e){result.errors.push(safeError(e));return result;}
 try{const db=await connection(ctx);await transaction(db,()=>baseline(db,false));result.core_health='PASS';}
 catch(e){result.core_health='CORE_PRODUCTION_DRIFT';result.core_error=safeError(e);result.result='ROLLED_BACK_CORE_DRIFT';}
 return result;
}
